[package]
name = "rs-clean"
version = "0.1.0"
edition = "2024"

[dependencies]
bytesize = "2.3.1"
clap = { version = "4.5.53", features = ["derive"] }
crossterm = "0.29.0"
ignore = "0.4.25"
num_cpus = "1.17.0"
ratatui = "0.29.0"
rayon = "1.11.0"
walkdir = "2.5.0"
